const styles = {
  colors: {
    primary: '#3579F5',
    primaryLight: '#E3F2FD',
    disabled: '#F3F3F3',
    disabledText: '#989898',
    actionGray: '#8a94a0',
    border: '#EBEBEB',
    highlight: '#3579F566',
    selectHighlight: '#3579F511',
    primaryText: '#FFFFFF',
    background: '#ffffff',
    titles: '#333',
    regular: 'rgba(32, 32, 32, 0.74)',
    grey: '#232323',
    gray: '#606060',
    grayLight: '#EEEFF1',
    grayDark: '#555555',
    gray4: '#C4C3C4',
    gray5: '#CCECEC',
    green: '#22C55E',
    white: '#FFFFFF',
    red: '#FF5C5C',
    yellow: '#dddd22',
    black: '#000000',
    transparent: '#FFFFFF00',
    dark: '#202020',
    input: '#333',
    inputBackground: '#66666611',
    placeholderColor: '#888888',
    // Добавленные цвета для экранов посредника
    success: '#22C55E',
    error: '#FF5C5C',
    errorLight: '#FFE5E5',
    successLight: '#E5F5E5',
    textSecondary: '#8a94a0',
    textDisabled: '#C0C0C0',
    lightGray: '#F5F5F5',
    info: '#3579F5',
    warning: '#FFA500',
  },
  borderR: 8,
  fonSize: {
    xxs: 10,
    xs: 12,
    sm: 14,
    smd: 16,
    md: 18,
    lg: 20,
    xl: 22,
    h2: 24,
    h1: 26,
    icon: 30,
    g1: 33,
    g2: 37,
    g3: 42,
    g4: 46,
  },
  lineHeight: {
    xxs: 14,
    xs: 16,
    sm: 18,
    smd: 20,
    md: 22,
    lg: 24,
    xl: 28,
    h2: 30,
    h1: 32,
    icon: 36,
    g1: 40,
    g2: 44,
    g3: 50,
    g4: 54,
  },
  padding: {
    xs: 1,
    sm: 2,
    md: 2,
    lg: 4,
    xl: 4,
  },
  paddingHorizontal: 12,

  // Стили для экрана смены пароля
  changePassword: {
    container: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 20,
      padding: 16,
    },
    description: {
      color: 'rgba(32, 32, 32, 0.74)', // styles.colors.regular
      fontSize: 18, // styles.fonSize.md
      fontWeight: '300',
      textAlign: 'left',
      width: '100%',
    },
    successContainer: {
      width: '100%',
      flex: 1,
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 24,
      paddingVertical: 60,
      paddingHorizontal: 16,
      minHeight: 400,
    },
    checkmarkContainer: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkmark: {
      width: 94,
      height: 94,
      borderRadius: 50,
      backgroundColor: '#E8F5E8', // Светло-зеленый фон
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    checkmarkText: {
      fontSize: 40,
      color: '#22C55E', // styles.colors.green
      fontWeight: 'bold',
    },
    checkmarkImage: {
      width: 95,
      height: 95,
    },
    buttonText: {
      color: '#fff',
    },
    successTitle: {
      fontFamily: 'Inter',
      fontWeight: '600',
      fontSize: 17,
      textAlign: 'center',
      color: '#323232',
    },
  },
};

export default styles;
