name: Mobile CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/mobile-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/mobile/**'

jobs:
  test:
    name: Test Mobile App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/mobile/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/mobile

      - name: Run linter
        run: npm run lint
        working-directory: apps/mobile

      - name: Run tests
        run: npm test -- --coverage --watchAll=false
        working-directory: apps/mobile

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: apps/mobile/coverage/lcov.info
          flags: mobile

  typescript:
    name: TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/mobile/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/mobile

      - name: TypeScript check
        run: npm run tsc -- --noEmit
        working-directory: apps/mobile
        continue-on-error: true

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [test, typescript]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm ci
        working-directory: apps/mobile

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug
        working-directory: apps/mobile

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: apps/mobile/android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: [test, typescript]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: apps/mobile

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
        working-directory: apps/mobile

      - name: Build iOS
        run: |
          xcodebuild -workspace ios/buildify.xcworkspace \
            -scheme buildify \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ios/build
        working-directory: apps/mobile
        continue-on-error: true

  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        working-directory: apps/mobile
        continue-on-error: true
